apiVersion: v1
kind: ConfigMap
metadata:
  name: is-aruco-config
  namespace: default
data:
  config: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_uri": "http://zipkin.default",
      "config": {
        "dictionary": "DICT_4X4_50",
        "lengths": {
          "0": 0.660
        }
      }
    }
---

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "is-aruco"
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: is-aruco
    spec:
      containers:
      - name: service 
        image: viros/is-aruco:0.0.2
        command: ["/service.bin"]
        args: ["/opt/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1.0"
            memory: 128Mi
        volumeMounts:
          - name: options
            mountPath: /opt
      volumes:
      - name: options
        configMap:
          name: is-aruco-config
          items:
          - key: config
            path: options.json
